# Generated by Django 3.0.7 on 2020-08-28 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketInfo',
            fields=[
                ('ticketId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=8)),
                ('time_hours', models.IntegerField()),
                ('time_minutes', models.IntegerField()),
            ],
        ),
    ]
