# Generated by Django 3.0.7 on 2020-08-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketinfo',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
