# Generated by Django 3.0.7 on 2020-08-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200828_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketinfo',
            name='movieName',
        ),
    ]
