# Generated by Django 3.0.7 on 2020-08-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_ticketinfo_moviename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketinfo',
            name='time_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
